apiVersion: v1
kind: Service
metadata:
  name: machineinfo-app
  namespace: machineinfo
  labels:
    app: machineinfo-app
spec:
  selector:
    app: machineinfo-app
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000